{
  lib,
  buildNpmPackage,
  fetchFromGitHub,
  nodejs,
  makeWrapper,
  pkg-config,
  libsecret,
}:

buildNpmPackage rec {
  pname = "brave-search-mcp-server";
  version = "2.0.83";

  src = fetchFromGitHub {
    owner = "brave";
    repo = "brave-search-mcp-server";
    rev = "v${version}";
    hash = "sha256-NYDXOxPQmjsZIEW/jEPUJ/Xfz9H0aZoWKuGaZJw2WjI=";
  };

  # The upstream lockfile (generated by npm 11) omits `resolved` URLs for
  # transitive dependencies. Replace with a lockfile regenerated by npm 10
  # that includes all `resolved` and `integrity` fields.
  postPatch = ''
    cp ${./package-lock.json} package-lock.json
  '';

  npmDepsHash = "sha256-LiYU43oqZn8qNG5LJOiQIVN2i+EkKWHciMWefW7ULi4=";

  nativeBuildInputs = [
    makeWrapper
    pkg-config
  ];

  buildInputs = [ libsecret ];

  installPhase = ''
    runHook preInstall

    mkdir -p $out/{bin,lib/brave-search-mcp-server}
    cp -r dist node_modules package.json $out/lib/brave-search-mcp-server/

    makeWrapper ${nodejs}/bin/node $out/bin/brave-search-mcp-server \
      --add-flags "$out/lib/brave-search-mcp-server/dist/index.js"

    runHook postInstall
  '';

  meta = with lib; {
    description = "Brave Search MCP Server: web search via the Model Context Protocol";
    homepage = "https://github.com/brave/brave-search-mcp-server";
    license = licenses.mit;
    mainProgram = "brave-search-mcp-server";
  };

  passthru.updateScript = [
    ../_update/run.sh
    "--attr"
    "brave-search-mcp-server"
    "--use-github-releases"
    "--pre-hook"
    "regen-npm-lockfile:brave/brave-search-mcp-server:v"
  ];
}
