{
  lib,
  buildNpmPackage,
  fetchFromGitHub,
  nodejs,
  makeWrapper,
}:

buildNpmPackage rec {
  pname = "multi-scrobbler";
  version = "0.14.1";

  src = fetchFromGitHub {
    owner = "FoxxMD";
    repo = "multi-scrobbler";
    rev = version;
    hash = "sha256-WrNheETW6snvtitL2IOcOQWBZgfLOIPO/x5Y8Q6lmTc=";
  };

  # The upstream lockfile (generated by npm 11) omits `resolved` URLs for
  # transitive dependencies. Replace with a lockfile regenerated by npm 10
  # that includes all `resolved` and `integrity` fields.
  postPatch = ''
    cp ${./package-lock.json} package-lock.json
  '';

  npmDepsHash = "sha256-yl448/xkaydQ+onozhrwi8CbgIgy5KcrBHnXg+PnwIE=";

  npmFlags = [ "--legacy-peer-deps" ];

  # Skip the default build which tries to build docs
  dontNpmBuild = true;

  nativeBuildInputs = [ makeWrapper ];

  buildPhase = ''
    runHook preBuild
    # Only build the frontend - backend runs via tsx
    npm run build:frontend
    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    mkdir -p $out/{bin,lib/multi-scrobbler}
    cp -r src dist node_modules package.json tsconfig.json $out/lib/multi-scrobbler/

    # Create wrapper script using tsx to run TypeScript directly
    # Use --chdir to set working directory so tsconfig.json can be found
    makeWrapper ${nodejs}/bin/node $out/bin/multi-scrobbler \
      --add-flags "$out/lib/multi-scrobbler/node_modules/.bin/tsx" \
      --add-flags "$out/lib/multi-scrobbler/src/backend/index.ts" \
      --set NODE_ENV production \
      --chdir "$out/lib/multi-scrobbler"

    runHook postInstall
  '';

  meta = with lib; {
    description = "Scrobble plays from multiple sources to multiple clients";
    homepage = "https://github.com/FoxxMD/multi-scrobbler";
    license = licenses.mit;
    maintainers = [ ];
    mainProgram = "multi-scrobbler";
  };

  passthru.updateScript = [
    ../_update/run.sh
    "--attr"
    "multi-scrobbler"
    "--use-github-releases"
    "--pre-hook"
    "regen-npm-lockfile:FoxxMD/multi-scrobbler::legacy-peer-deps"
  ];
}
