{
  lib,
  buildNpmPackage,
  fetchFromGitHub,
  nodejs,
  makeWrapper,
}:

buildNpmPackage rec {
  pname = "multi-scrobbler";
  version = "0.16.5";

  src = fetchFromGitHub {
    owner = "FoxxMD";
    repo = "multi-scrobbler";
    rev = version;
    hash = "sha256-EqJ265SGFlYGyxnKQciDPjATzznniKfEYbjYEDwjzMY=";
  };

  # The upstream lockfile (generated by npm 11) omits `resolved` URLs for
  # transitive dependencies. Replace with a lockfile regenerated by npm 10
  # that includes all `resolved` and `integrity` fields.
  postPatch = ''
    cp ${./package-lock.json} package-lock.json
  '';

  npmDepsHash = "sha256-WdCZW30tZI/DStijhsoQt5w3nQ+rUP5aEZ1CarcQ8ig=";

  # `--ignore-scripts` blocks dependency lifecycle scripts during `npm ci`.
  # As of 0.14.2 the `storybook-addon-remix-react-router` devDependency has a
  # `preinstall` of `npx only-allow pnpm`, which reaches the network (fetching
  # `only-allow`) and fails in the sandbox. The frontend build (`vite build`)
  # needs no install scripts — esbuild/rollup resolve prebuilt binaries from
  # their vendored `@esbuild/linux-x64`-style platform packages.
  npmFlags = [
    "--legacy-peer-deps"
    "--ignore-scripts"
  ];

  # Skip the default build which tries to build docs
  dontNpmBuild = true;

  nativeBuildInputs = [ makeWrapper ];

  # multi-scrobbler ships fixes to several of its dependencies as patch-package
  # patches (patches/*.patch), normally applied by its `postinstall:
  # patch-package`. Since `npm ci` runs with `--ignore-scripts` (above), apply
  # them explicitly here — after node_modules is populated, before it's copied
  # into $out. The sqlite-up patch is load-bearing: it makes Migrator.apply()
  # forward the migration context to each migration's `up(db, ctx)`, without
  # which app migrations (e.g. 001_lifecycleLoc) crash dereferencing an
  # undefined `ctx`. patch-package (a devDependency, present in node_modules)
  # skips the non-`.patch` files and applies each patch offline.
  preBuild = ''
    node_modules/.bin/patch-package
  '';

  buildPhase = ''
    runHook preBuild
    # Only build the frontend - backend runs from source via node type stripping
    npm run build:frontend
    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    mkdir -p $out/{bin,lib/multi-scrobbler}
    cp -r src dist node_modules package.json tsconfig.json $out/lib/multi-scrobbler/

    # As of 0.15.0 upstream requires node >=24.14.0 and runs the TypeScript
    # entrypoint directly via node's native type stripping (`tsx` was dropped
    # from the dep tree) — matching upstream's own service script:
    # `node /app/src/backend/index.ts`.
    # Use --chdir to set working directory so tsconfig.json can be found
    makeWrapper ${nodejs}/bin/node $out/bin/multi-scrobbler \
      --add-flags "$out/lib/multi-scrobbler/src/backend/index.ts" \
      --set NODE_ENV production \
      --chdir "$out/lib/multi-scrobbler"

    runHook postInstall
  '';

  meta = with lib; {
    description = "Scrobble plays from multiple sources to multiple clients";
    homepage = "https://github.com/FoxxMD/multi-scrobbler";
    license = licenses.mit;
    maintainers = [ ];
    mainProgram = "multi-scrobbler";
  };

  passthru.updateScript = [
    ../_update/run.sh
    "--attr"
    "multi-scrobbler"
    "--use-github-releases"
    "--pre-hook"
    "regen-npm-lockfile:FoxxMD/multi-scrobbler::legacy-peer-deps"
  ];
}
